version: '3.8'

services:
    app:
        build:
            context: .
        environment:
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=secret  # Устанавливаем пароль для root пользователя
            - MYSQL_DATABASE=laravel
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql_data:
        driver: local
